name: 0.1.$(Rev:r)

trigger:
  batch: true
  paths:
    include:
      - nodebrady/charts
      - nodebrady/azure-pipelines.helm.yaml
  branches:
    include:
      - main

variables:
  - group: acr
  - name: containerRepository
    value: nodebrady
  - name: chart_path
    value: nodebrady/charts/nodebrady
  - name: namespace
    value: charts
  - name: HELM_EXPERIMENTAL_OCI
    value: 1
  - name: artifact
    value: "$(LOGIN_SERVER)/$(namespace)/$(containerRepository):$(Build.BuildNumber)"

stages:
  - template: '../pipeline-templates/helm-package.yml'