name: 0.1.$(Rev:r)

trigger:
  batch: true
  paths:
    include:
      - phippy/charts
      - phippy/azure-pipelines.helm.yaml
  branches:
    include:
      - main

variables:
  - group: acr
  - name: containerRepository
    value: phippy
  - name: chart_path
    value: phippy/charts/phippy
  - name: namespace
    value: charts
  - name: HELM_EXPERIMENTAL_OCI
    value: 1
  - name: artifact
    value: "$(LOGIN_SERVER)/$(namespace)/$(containerRepository):$(Build.BuildNumber)"

stages:
  - template: '../pipeline-templates/helm-package.yml'