name: 0.2.$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/stages/kubernetes-dev
      - infrastructure/azure-pipelines.kubernetes-dev.yml

pr:
  autoCancel: true
  drafts: true
  branches:
    include:
      - main

variables:
  - template: '../pipeline-templates/infrastructure-variables.yml'
  - name: projectFolder
    value: infrastructure/stages/kubernetes-dev
  - name: kubernetesCluster
    value: aks-boss-crawdad-dev

stages:
  - template: '../pipeline-templates/kubernetes-plan.yml'
    parameters:
      projectFolder: $(projectFolder)
      stateBlobName: kubernetes-dev.terraform.tfstate

  - template: '../pipeline-templates/kubernetes-deploy.yml'
    parameters:
      environment: kubernetes-dev
      projectFolder: $(projectFolder)
      kubernetesCluster: $(kubernetesCluster)
